version: '2'
services:
  openldap:
    environment:
      LDAP_ORGANISATION: "Example Inc."
      LDAP_DOMAIN: "example.com"
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_CONFIG_PASSWORD: "config"
    image: osixia/openldap:latest
    ports:
      - "389:389"
      - "636:636"
    expose:
      - "389"
  phpldapadmin:
    depends_on:
      - openldap
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
    image: osixia/phpldapadmin:latest
    ports:
      - "8443:443"
