# Add the following ldif to the LDAP server

## LDIF Export for cn=importtestignore,dc=example,dc=com
## Server: openldap (openldap)
## Search Scope: base
## Search Filter: (objectClass=*)
## Total Entries: 1
##
## Generated by phpLDAPadmin (http://phpldapadmin.sourceforge.net) on September 18, 2023 8:46 am
## Version: 1.2.5
#
#version: 1
#
## Entry 1: cn=importtestignore,dc=example,dc=com
#dn: cn=importtestignore,dc=example,dc=com
#cn: importtestignore
#description: test
#objectclass: person
#objectclass: top
#sn: test

# Then run LDAP_URL=... LDAP_ADMIN=... LDAP_PASSWORD=... terraform import ldap_object.importtestignore cn=importtestignore,dc=example,dc=com
# Then run LDAP_URL=... LDAP_ADMIN=... LDAP_PASSWORD=... terraform apply
# There should not be any changes to the object

resource "ldap_object" "importtestignore" {
  dn = "cn=importtestignore,dc=example,dc=com"
  object_classes = ["person", "top"]

  attributes = {
    "cn" = ["importtestignore"]
    "sn" = ["test"]
    "description" = ["testchange"]
  }

  ignore_changes = ["description"]
}